name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake .. -G"Visual Studio 15 2017"
    - name: build
      run: cmake --build build --config Debug
    - name: Download a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}/build/glquake/**/*.exe && ${{ github.workspace }}/build/glquake/**/*.dll && ${{ github.workspace }}/game_root/
